# Generated by Django 5.1.6 on 2025-03-08 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='course-covers/', verbose_name='cover')),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('DW', 'Desenvolvimento Web'), ('DM', 'Desenvolvimento Mobile'), ('CD', 'Ciência de Dados'), ('RC', 'Redes de Computadores'), ('Outro', 'Outro')], default='Outro', max_length=20, null=True)),
                ('publiced_at', models.DateField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('uuid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('language', models.CharField(blank=True, choices=[('PT', 'Português'), ('EN', 'Ingles')], default='PT', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('stars', models.ManyToManyField(related_name='courses_with_user_stars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preview', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='video-cover/')),
                ('video', models.FileField(blank=True, null=True, upload_to='course-videos/', verbose_name='videos')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_preview', to='courses.video'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos_comment', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.video')),
            ],
        ),
    ]
