# Generated by Django 5.1.4 on 2025-02-25 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROGRAMAÇÃO", "PROGRAMAÇÃO"),
                            ("REDES", "REDES"),
                            ("ELETRÓNICA", "ELETRÓNICA"),
                            ("ANÓNIMO", "ANÓNIMO"),
                            ("OUTROS", "OUTROS"),
                        ],
                        default="ANÓNIMO",
                        max_length=50,
                    ),
                ),
                ("date_publiced", models.DateField()),
                ("slug", models.SlugField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("slug", models.SlugField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "path",
                    models.FileField(
                        upload_to="course-videos/", verbose_name="video_path"
                    ),
                ),
                ("slug", models.SlugField(default=None)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.teacher",
                    ),
                ),
            ],
        ),
    ]
