# Generated by Django 5.1.6 on 2025-03-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
