# Generated by Django 5.1.4 on 2025-02-25 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="teacher",
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="None"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="slug",
            field=models.SlugField(default="None"),
        ),
        migrations.AlterField(
            model_name="video",
            name="slug",
            field=models.SlugField(default="None"),
        ),
    ]
