# Generated by Django 5.1.4 on 2025-02-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_remove_video_teacher_course_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
