# Generated by Django 5.1.6 on 2025-03-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_name_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FileField(max_length=500, upload_to='course-videos/', verbose_name='video_path'),
        ),
    ]
