# Generated by Django 5.1.4 on 2025-03-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_video_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("PROGRAMAÇÃO", "PROGRAMAÇÃO"),
                    ("ELETRÓNICA", "ELETRÓNICA"),
                    ("OUTROS", "OUTROS"),
                    ("REDES", "REDES"),
                ],
                default="OUTROS",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
