# Generated by Django 5.1.6 on 2025-03-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_comment'),
        ('library', '0023_alter_sugestion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RenameField(
            model_name='video',
            old_name='curso',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_publiced',
        ),
        migrations.RemoveField(
            model_name='video',
            name='path',
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(related_name='courses', to='library.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='course-covers/', verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='course-preview/', verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='course',
            name='publiced_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course-videos/', verbose_name='videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
