# Generated by Django 5.1.6 on 2025-03-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_teacher_rename_curso_video_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('DW', 'Desenvolvimento Web'), ('DM', 'Desenvolvimento Mobile'), ('CD', 'Ciência de Dados'), ('RC', 'Redes de Computadores'), ('Outro', 'Outro')], default='Outro', max_length=20, null=True),
        ),
    ]
