# Generated by Django 5.1.4 on 2025-03-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_alter_course_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
