# Generated by Django 5.1.6 on 2025-03-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
