# Generated by Django 5.1.6 on 2025-03-07 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_comment_content_alter_comment_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stars',
            field=models.ManyToManyField(related_name='courses_with_user_stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
