# Generated by Django 5.1.4 on 2025-03-07 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_course_description"),
        ("courses", "0014_course_description"),
    ]

    operations = []
