# Generated by Django 5.1.6 on 2025-03-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
