# Generated by Django 5.1.4 on 2025-03-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_merge_0010_course_description_0014_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
