# Generated by Django 5.1.6 on 2025-03-08 09:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Processo')),
                ('grade', models.CharField(choices=[('10', 'Décima'), ('11', 'Décima Primeira'), ('12', 'Décima Segunda'), ('13', 'Décima Terceira')], max_length=3, verbose_name='Classe')),
                ('course', models.CharField(choices=[('Informática', 'Informática'), ('Eletrónica', 'Eletrónica')], max_length=30, verbose_name='Curso')),
                ('group', models.CharField(choices=[('A', 'Turma A'), ('B', 'Turma B'), ('C', 'Turma C'), ('D', 'Turma D')], max_length=1, verbose_name='Turma')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador Universal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
