# Generated by Django 5.1.4 on 2024-12-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='grade',
            field=models.IntegerField(choices=[(10, '10ª'), (11, '11ª'), (12, '12ª'), (13, '13ª')]),
        ),
    ]
