# Generated by Django 5.1.6 on 2025-03-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile-photos/'),
        ),
    ]
