# Generated by Django 5.1.4 on 2024-12-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_reader_course_alter_reader_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='course',
            field=models.CharField(choices=[('informatica', 'Informatica'), ('eletronica', 'Electronica')], max_length=30),
        ),
    ]
