# Generated by Django 5.1.4 on 2024-12-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_alter_reader_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='group',
            field=models.CharField(choices=[('C', 'Turma C'), ('D', 'Turma D'), ('B', 'Turma B'), ('A', 'Turma A')], max_length=3, verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='photo',
            field=models.FileField(upload_to='profiles-photo/', verbose_name='Perfil'),
        ),
    ]
