# Generated by Django 5.1.4 on 2025-01-02 00:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0010_alter_reader_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reader",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="reader",
            name="slug",
        ),
        migrations.AddField(
            model_name="reader",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Identificador Universal",
            ),
        ),
        migrations.AlterField(
            model_name="reader",
            name="group",
            field=models.CharField(
                choices=[
                    ("A", "Turma A"),
                    ("B", "Turma B"),
                    ("C", "Turma C"),
                    ("D", "Turma D"),
                ],
                max_length=1,
                verbose_name="Turma",
            ),
        ),
        migrations.AlterField(
            model_name="reader",
            name="process_number",
            field=models.IntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Número de Processo",
            ),
        ),
    ]
